name: Format Check

on:
  push:
    branches-ignore: [main]
  workflow_dispatch: # manually triggered using 'Run workflow' from the web interface

# environment variables set from repository secrets
env:
  TF_VAR_STATE_ENCRYPTION_PASSPHRASE: ${{ secrets.TF_VAR_STATE_ENCRYPTION_PASSPHRASE }}

jobs:
  format-check:
    name: Format Check
    permissions:
      contents: read # allow git checkouts
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: copy .env
        run: cp .env.example .env

      - name: tofu fmt check
        run: make tofu_fmt_check
